// Generated by tools/generate_runtime.py from wallpapers/*.html.
import { DEFAULT_OPTIONS, imageToAsciiFrame } from './asciify-core.js';
import { FluidField, texture } from './fluid-field.js';
const scenes = {};
scenes["fluid"] = function(asciipaper) {

// The Asciify "Fluid" background (asciify.org/docs/backgrounds/fluid), offline, on the GPU.
// FluidField (pointer wake) is ported verbatim from asciify-engine src/surface/fluid-field.ts;
// paintLiquidSource + the site's amber tint are the same math, in GLSL. Which character each cell
// gets is decided by the unmodified engine (lib/asciify-core.js): its luminance→glyph table is read
// once at startup. MIT, © ayangabryl — see ../licenses/asciify-engine-MIT.txt.
// Rendering is lib/asciipaper.js; per frame, JS only steps the small pointer field.
// Knobs: MIN_FONT = glyph cell px (asciify.org uses 7; smaller = finer); MAX_GLYPHS caps density.

const MIN_FONT = 7, MAX_GLYPHS = 26e3;
const OPTIONS = { ...DEFAULT_OPTIONS, fontSize: 7, charAspect: .58, charset: ' .:+-=xICA$FY#@',
  colorMode: 'fullcolor', accentColor: '#e8b900', normalize: false, contrast: .1, hoverStrength: 0, chromaKey: null };
const CHARS = OPTIONS.charset;

// Ask the engine which glyph each luminance 0..255 gets (256 one-pixel cells over a gray ramp).
const ramp = document.createElement('canvas'); ramp.width = 256; ramp.height = 1;
const rampContext = ramp.getContext('2d'), rampImage = rampContext.createImageData(256, 1);
for (let i = 0; i < 256; i++) rampImage.data.set([i, i, i, 255], i * 4);
rampContext.putImageData(rampImage, 0, 0);
const lut = imageToAsciiFrame(ramp, { ...OPTIONS, fontSize: 1, charAspect: 1, charSpacing: 1 }, 256, 1).frame[0]
  .map(cell => Math.max(0, CHARS.indexOf(cell.char)));

// liquid source → amber tint (as on asciify.org) → luminance, which picks the glyph through `lut`.
const glsl = `uniform sampler2D flow;uniform float moving;
vec4 cell(vec2 uv){
  vec3 f=moving>0.5?(texture2D(flow,uv).rgb-vec3(0.5,0.5,0.0))*vec3(0.36,0.36,0.8):vec3(0.0);
  float time=u_time;
  float px=(uv.x-0.5-f.x)*u_aspect, py=uv.y-0.5-f.y;
  float qx=px+0.22*sin(py*5.2+time*0.17)+0.15*sin(px*2.4-py*3.1-time*0.1);
  float qy=py+0.19*sin(px*3.5+time*0.13);
  float radius=length(vec2(qx*0.8+0.18,qy*1.1));
  float folds=0.5+0.5*sin(radius*14.0-qx*2.8+sin(qy*5.0)*1.4-time*0.24);
  float cloud=0.5+0.5*sin(qx*3.6-qy*2.9+time*0.09);
  float light=clamp(folds*folds*(0.48+cloud*0.32)-0.075+f.z*0.75,0.0,1.0);
  float value=floor(light*255.0+0.5);
  float r=value<10.0?0.0:min(255.0,value*1.45), g=r*185.0/232.0;
  return vec4(r/255.0,g/255.0,0.0,floor(0.299*r+0.587*g)/255.0);
}`;

let flow, flowBytes;
const uploadFlow = scene => scene.texture('flow', flow.columns, flow.rows, texture(flow, flowBytes));

asciipaper.ascii({
  canvas: document.getElementById('c'), charset: CHARS, glsl, lut, cell: MIN_FONT, aspect: OPTIONS.charAspect, maxCells: MAX_GLYPHS,
  background: '#000000', font: '"JetBrains Mono", monospace',
  time: 12, period: 200 * Math.PI,                 // every sin coefficient is a multiple of .01 → exact period
  resize(scene) {
    flow = new FluidField(scene.width / scene.height); flowBytes = new Uint8Array(flow.columns * flow.rows * 4);
    uploadFlow(scene);
  },
  update(scene, dt) {
    flow.step(Math.min(.05, dt));
    const moving = flow.active;
    if (moving) uploadFlow(scene);
    scene.uniforms.moving = moving ? 1 : 0;
  },
});
addEventListener('pointermove', e => flow.move(e.clientX / innerWidth, e.clientY / innerHeight, asciipaper.options.pointer));
addEventListener('pointerleave', () => flow.leave());

};
scenes["flow"] = function(asciipaper) {

// Offline interactive ASCII fluid. Stable-fluids style: inject → advect → project, on the CPU;
// lib/asciipaper.js turns the density grid into glyphs on the GPU.
// Knobs: cell/aspect below = glyph cell (bigger = faster, coarser). ITER = pressure solve iterations.
const ITER = 4, RAMP = ' .:-=+*#%@';
let cols, rows, N, vx, vy, vx0, vy0, d, d0, p, div;
const colors = [...RAMP].map((_, i) => {         // hsl(165 70% 25..80%) → rgb 0..1
  const l = .25 + .55 * i / RAMP.length, a = .7 * Math.min(l, 1 - l);
  const f = n => { const k = (n + 165 / 30) % 12; return l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1)); };
  return [f(0), f(8), f(4)];
});

const I = (i, j) => i + j * cols;
function sample(f, fx, fy) {                       // bilinear
  fx = Math.max(0, Math.min(cols - 1.001, fx)); fy = Math.max(0, Math.min(rows - 1.001, fy));
  const i = fx | 0, j = fy | 0, s = fx - i, t = fy - j, k = I(i, j);
  return (f[k] * (1 - s) + f[k + 1] * s) * (1 - t) + (f[k + cols] * (1 - s) + f[k + cols + 1] * s) * t;
}
function advect(dst, src, decay) {
  for (let j = 0; j < rows; j++) for (let i = 0; i < cols; i++) {
    const k = I(i, j);
    dst[k] = sample(src, i - vx0[k], j - vy0[k]) * decay;
  }
}
function project() {                              // make velocity divergence-free
  for (let j = 1; j < rows - 1; j++) for (let i = 1; i < cols - 1; i++) {
    const k = I(i, j);
    div[k] = -0.5 * (vx[k + 1] - vx[k - 1] + vy[k + cols] - vy[k - cols]); p[k] = 0;
  }
  for (let n = 0; n < ITER; n++)
    for (let j = 1; j < rows - 1; j++) for (let i = 1; i < cols - 1; i++) {
      const k = I(i, j);
      p[k] = (div[k] + p[k - 1] + p[k + 1] + p[k - cols] + p[k + cols]) / 4;
    }
  for (let j = 1; j < rows - 1; j++) for (let i = 1; i < cols - 1; i++) {
    const k = I(i, j);
    vx[k] -= 0.5 * (p[k + 1] - p[k - 1]); vy[k] -= 0.5 * (p[k + cols] - p[k - cols]);
  }
}
function splat(cx, cy, fx, fy, dens, r) {
  for (let j = Math.max(1, cy - r | 0); j < Math.min(rows - 1, cy + r); j++)
    for (let i = Math.max(1, cx - r | 0); i < Math.min(cols - 1, cx + r); i++) {
      const w = Math.max(0, 1 - Math.hypot(i - cx, j - cy) / r), k = I(i, j);
      vx[k] += fx * w; vy[k] += fy * w; d[k] = Math.min(1.5, d[k] + dens * w);
    }
}

let t = 0, mx = -1, my = -1, pmx = -1, pmy = -1;
addEventListener('pointermove', e => { mx = e.clientX / innerWidth * cols; my = e.clientY / innerHeight * rows; });
addEventListener('pointerdown', e => splat(e.clientX / innerWidth * cols, e.clientY / innerHeight * rows, 0, 0, 1.5, 8));

asciipaper.ascii({
  charset: RAMP, cell: 10, aspect: 10 / 16, background: '#080909',
  resize(scene) {
    cols = scene.cols; rows = scene.rows; N = cols * rows;
    [vx, vy, vx0, vy0, d, d0, p, div] = Array.from({ length: 8 }, () => new Float32Array(N));
  },
  update(scene) {
    t += 0.016;
    const strength = asciipaper.options.pointer;
    if (mx >= 0 && pmx >= 0) splat(mx, my, (mx - pmx) * 0.6 * strength, (my - pmy) * 0.6 * strength, 0.35 * strength, 4);
    pmx = mx; pmy = my;
    for (let s = 0; s < 3; s++) {                    // ambient drift so it lives without a cursor
      const a = t * 0.25 + s * 2.1, cx = cols * (0.5 + 0.35 * Math.cos(a + s)), cy = rows * (0.5 + 0.35 * Math.sin(a * 0.7));
      splat(cx, cy, -Math.sin(a) * 0.15, Math.cos(a) * 0.15, 0.03, 6);
    }
    vx0.set(vx); vy0.set(vy); advect(vx, vx0, 0.995); advect(vy, vy0, 0.995);
    project();
    vx0.set(vx); vy0.set(vy); d0.set(d); advect(d, d0, 0.985);
    for (let k = 0; k < N; k++) {
      const v = d[k], l = v < 0.03 ? 0 : Math.min(RAMP.length - 1, v * RAMP.length | 0), c = colors[l];
      scene.put(k % cols, k / cols | 0, l / (RAMP.length - 1), c[0], c[1], c[2]);
    }
  },
});

};
scenes["matrix"] = function(asciipaper) {

// Digital rain, computed per cell on the GPU: each column's drop position is a function of time,
// so there is no state to update. The rain brightens and scrambles near the pointer; clicks ripple.
const CHARS = ' ｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉ0123456789ABCDEF';
asciipaper.ascii({
  charset: CHARS, cell: 16, aspect: 1, background: '#000000', font: 'monospace',
  glsl: `
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
vec4 cell(vec2 uv){
  vec2 c=floor(uv*u_grid);                                  // column, row (row 0 = top)
  float speed=5.0+hash(vec2(c.x,1.0))*9.0, len=6.0+hash(vec2(c.x,2.0))*22.0;
  float span=u_grid.y+len+hash(vec2(c.x,3.0))*50.0;         // rows until this column's next drop
  float d=mod(u_time*speed+hash(vec2(c.x,4.0))*span,span)-c.y;   // rows behind the drop's head
  float b=d>=0.0&&d<len?1.0-d/len:0.0;
  float near=u_strength*smoothstep(0.2,0.0,length((uv-u_pointer)*vec2(u_aspect,1.0)))*step(u_idle,2.0);
  float ring=0.0;
  for(int i=0;i<8;i++){vec3 k=u_clicks[i];
    ring=max(ring,smoothstep(0.025,0.0,abs(length((uv-k.xy)*vec2(u_aspect,1.0))-k.z*0.5))*max(0.0,1.0-k.z/1.6));}
  b=max(max(b,near*0.35),ring);
  if(b<0.03)return vec4(0.0);
  float flip=floor(u_time*(1.5+near*25.0)+hash(c)*9.0);     // glyphs change now and then, fast near the cursor
  float glyph=1.0+floor(hash(c+flip*vec2(1.7,9.2))*${CHARS.length - 1}.0);
  vec3 color=d>=0.0&&d<1.0?vec3(0.8,1.0,0.8):vec3(0.0,1.0,0.27)*b;
  return vec4(color,glyph/${CHARS.length - 1}.0);
}`,
});

};
scenes["yin-yang"] = function(asciipaper) {

// A slowly turning ASCII taijitu. It doesn't chase the pointer: moving the pointer stirs a liquid
// (lib/fluid-field.js) that bends the emblem and lights it where it flows, then settles.

const CHARS = ' .,:;irsXA253hMHGS#9B&@·';            // '·' (last) is only used by ripples
let angle = 0, flow, bytes;
const upload = scene => scene.texture('flow', flow.columns, flow.rows, texture(flow, bytes));
asciipaper.ascii({
  charset: CHARS, cell: 9, aspect: 9 / 15, background: '#080909',
  resize(scene) {
    flow = new FluidField(scene.width / scene.height); bytes = new Uint8Array(flow.columns * flow.rows * 4);
    upload(scene);
  },
  update(scene, dt) {
    angle += dt * 0.24;
    scene.uniforms.radius = Math.max(30, Math.min(scene.width * .31, scene.height * .40));
    scene.uniforms.center = [scene.width * .5, scene.height * .5];
    scene.uniforms.rot = angle;
    flow.step(Math.min(.05, dt));
    const moving = flow.active;
    if (moving) upload(scene);
    scene.uniforms.moving = moving ? 1 : 0;
  },
  glsl: `uniform vec2 center;uniform float radius,rot,moving;uniform sampler2D flow;
vec4 cell(vec2 uv){
  vec3 f=moving>0.5?(texture2D(flow,uv).rgb-vec3(0.5,0.5,0.0))*vec3(0.36,0.36,0.8):vec3(0.0);
  vec2 s=(uv-f.xy*0.9)*u_size-center;                        // the liquid bends what's under it
  float ca=cos(rot),sa=sin(rot);
  vec2 q=vec2(s.x*ca+s.y*sa,-s.x*sa+s.y*ca)/radius;
  float r=length(q);
  float ring=0.0;
  for(int i=0;i<8;i++){vec3 k=u_clicks[i];
    if(k.z<1.3)ring=max(ring,(1.0-k.z/1.3)*step(abs(length((uv-k.xy)*u_size)-k.z*0.7*radius),5.0));}
  if(ring>0.0)return vec4(vec3(143.0,230.0,218.0)/255.0*ring*0.7+0.1,1.0);
  if(r>1.035)return vec4(vec3(143.0,230.0,218.0)/255.0*f.z,f.z*0.5);   // ink on the dark around it
  bool white=q.x-0.42*sin(3.14159265*q.y)<0.0;             // the S-shaped halves...
  if(length(q-vec2(0.0,0.5))<0.14)white=false;               // ...and the two opposing dots
  if(length(q+vec2(0.0,0.5))<0.14)white=true;
  float grain=(sin(q.x*32.0+q.y*17.0)+cos(q.y*29.0-q.x*13.0))*0.5;
  float shade=clamp(floor((r>0.92?0.55:0.58+grain*0.12)*22.0),0.0,22.0);
  float glow=max(0.0,1.0-length(s/u_size)*2.3)+f.z*0.8;
  vec3 color=white?(vec3(196.0,208.0,206.0)+glow*vec3(59.0,47.0,49.0))/255.0
                  :(vec3(30.0,91.0,91.0)+glow*vec3(24.0,55.0,55.0))/255.0;
  return vec4(color,shade/23.0);
}`,
});
addEventListener('pointermove', e => flow?.move(e.clientX / innerWidth, e.clientY / innerHeight, asciipaper.options.pointer));
addEventListener('pointerleave', () => flow?.leave());

};
export function run(name, spec) {
  const api=window.asciipaper; let result;
  const {shader,glsl,scene,media,mediaUrl,uniforms,...look}=spec;
  const facade={...api,ascii:config=>result=api.ascii({...config,...look,glsl:config.glsl,update(s,dt){
    config.update?.(s,dt);
    for(const [k,v] of Object.entries(uniforms||{}))s.uniforms[k]=typeof v==='string'&&/^#[a-f0-9]{6}$/i.test(v)?[1,3,5].map(i=>parseInt(v.slice(i,i+2),16)/255):v;
  }})};
  if(!scenes[name])throw new Error('Unknown scene: '+name);
  scenes[name](facade); return result;
}
