#!/usr/bin/env python3
"""Generate native/mobile resources from the existing web renderer and look catalog.

Run after editing wallpapers/lib/asciipaper.js or looks.json. --check is read-only
and is used by CI/builds to reject stale resources before platforms can diverge.
"""
import argparse
import ast
import json
from pathlib import Path
import re
import math

ROOT = Path(__file__).resolve().parents[1]
NAMES = ("HEADER", "QUAD", "CELL_MAIN", "GLYPHS")
LEGACY = ("fluid", "flow", "matrix", "yin-yang")


def legacy_resources(root):
    """Package the existing scene scripts and C descriptors without maintaining new copies."""
    native = (root / "native/presets.c").read_text()
    js = '// Generated by tools/generate_runtime.py from wallpapers/*.html.\n'
    js += "import { DEFAULT_OPTIONS, imageToAsciiFrame } from './asciify-core.js';\nimport { FluidField, texture } from './fluid-field.js';\nconst scenes = {};\n"
    outputs = {}
    for name in LEGACY:
        variable = name.replace('-', '_')
        body = re.search(r"static const struct preset " + variable + r" = \{(.*?)\n\};", native, re.S)[1]
        shader = re.search(r'\.glsl\s*=\s*((?:"(?:[^"\\]|\\.)*"\s*)+),', body)
        shader = ''.join(ast.literal_eval(v) for v in re.findall(r'"(?:[^"\\]|\\.)*"', shader[1])) if shader else 'vec4 cell(vec2 uv){return texture2D(u_data,uv);}'
        spec = {"title": name, "scene": name, "shader": shader}
        for key in ("charset", "background", "font"):
            value = re.search(r'\.' + key + r'\s*=\s*("(?:[^"\\]|\\.)*")', body)
            if value:
                spec[key] = ast.literal_eval(value[1])
        for key, field in (("cell","cell"),("aspect","aspect"),("maxCells","max_cells"),("time","time"),("period","period")):
            value = re.search(r'\.' + field + r'\s*=\s*([^,\n]+)', body)
            if value:
                expression = re.sub(r'(?<=[\d.])f\b', '', value[1]).replace('M_PI', str(math.pi))
                tree = ast.parse(expression, mode='eval')
                if any(not isinstance(n, (ast.Expression,ast.Constant,ast.BinOp,ast.Mult,ast.Div,ast.Add,ast.Sub,ast.UnaryOp,ast.USub)) for n in ast.walk(tree)):
                    raise ValueError('Unsupported scene descriptor: ' + expression)
                spec[key] = eval(compile(tree,'scene descriptor','eval'),{"__builtins__":{}})
        outputs['wallpapers/specs/' + name + '.json'] = json.dumps(spec, ensure_ascii=False, indent=2) + '\n'
        html = (root / 'wallpapers' / (name + '.html')).read_text()
        script = re.findall(r'<script(?: type="module")?>(.*?)</script>',html,re.S)[-1]
        script = re.sub(r'^import .*?;\n', '', script, flags=re.M)
        js += 'scenes[' + json.dumps(name) + '] = function(asciipaper) {\n' + script + '\n};\n'
    js += '''export function run(name, spec) {
  const api=window.asciipaper; let result;
  const {shader,glsl,scene,media,mediaUrl,uniforms,...look}=spec;
  const facade={...api,ascii:config=>result=api.ascii({...config,...look,glsl:config.glsl,update(s,dt){
    config.update?.(s,dt);
    for(const [k,v] of Object.entries(uniforms||{}))s.uniforms[k]=typeof v==='string'&&/^#[a-f0-9]{6}$/i.test(v)?[1,3,5].map(i=>parseInt(v.slice(i,i+2),16)/255):v;
  }})};
  if(!scenes[name])throw new Error('Unknown scene: '+name);
  scenes[name](facade); return result;
}
'''
    outputs['wallpapers/lib/legacy.js'] = js
    return outputs


def shaders(source):
    result = {}
    for name in NAMES:
        match = re.search(r"\bconst " + name + r" = ([`'])(.*?)\1;", source, re.S)
        if not match:
            raise ValueError(f"Missing shader constant {name}")
        text = match[2]
        # Fail explicitly if JS syntax stops being a literal shader. Never ship a
        # partially extracted shader or silently interpret JS escapes as GLSL.
        if "${" in text or "\\" in text:
            raise ValueError(f"{name}: use a literal GLSL string without interpolation/escapes")
        result[name] = text
    return result


def resources(root=ROOT):
    source = (root / "wallpapers/lib/asciipaper.js").read_text()
    catalog = json.loads((root / "wallpapers/lib/looks.json").read_text())
    tables = {"SHAPES": catalog["shapes"], "DITHERS": catalog["dithers"], "FX": list(catalog["effects"])}
    for name, values in tables.items():
        match = re.search(r"\bconst " + name + r" = (\[.*?\]);", source)
        if not match or [v for v in ast.literal_eval(match[1]) if v] != values:
            raise ValueError(f"{name}: web renderer indices must match looks.json order")
    parts = shaders(source)
    header = "// Generated by tools/generate_runtime.py; edit wallpapers/lib/asciipaper.js.\n#pragma once\n"
    for name, text in parts.items():
        header += f"static const char {name}[] =\n"
        header += "\n".join("    " + json.dumps(line) for line in text.splitlines(keepends=True)) + ";\n"
    names = "// Generated by tools/generate_runtime.py; edit wallpapers/lib/looks.json.\n#pragma once\n"
    for name, values in tables.items():
        names += f"static const char *const {name}[] = {{" + ", ".join(json.dumps(v) for v in values) + ", NULL};\n"
    outputs = {"native/shaders.h": header, "native/look_names.h": names}
    outputs.update(legacy_resources(root))
    entries = []
    paths = {p.name: json.loads(p.read_text()) for p in (root / "wallpapers/specs").glob("*.json") if p.stem not in LEGACY}
    paths.update({n + '.json': json.loads(outputs['wallpapers/specs/' + n + '.json']) for n in LEGACY})
    for file, spec in sorted(paths.items()):
        path = Path(file)
        relative = "specs/" + path.name
        entries.append({"name": path.stem, "title": spec.get("title", path.stem), "kind": "spec",
                        "url": "run.html?spec=" + relative, "spec": relative})
    outputs["wallpapers/catalog.json"] = json.dumps(entries, indent=2) + "\n"
    outputs["wallpapers/lib/shaders/look-indices.json"] = json.dumps(tables, indent=2) + "\n"
    for name, text in parts.items():
        outputs[f"wallpapers/lib/shaders/{name.lower()}.glsl"] = text.rstrip("\n") + "\n"
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, text in resources().items():
        path = ROOT / name
        if path.exists() and path.read_text() == text:
            continue
        stale.append(name)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if args.check and stale:
        parser.exit(1, "Stale runtime resources: " + ", ".join(stale) + "\nRun python3 tools/generate_runtime.py\n")
    print("Runtime resources current" if args.check else f"Generated {len(stale)} runtime resources")


if __name__ == "__main__":
    main()
